//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workspaces_Meeting_Rooms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WMRDBEntities : DbContext
    {
        public WMRDBEntities()
            : base("name=WMRDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<reservation> reservations { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<roomsEquipment> roomsEquipments { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<UsageStatistic> UsageStatistics { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
